# You are given three positive integers num1, num2, and num3.
#
# The key of num1, num2, and num3 is defined as a four-digit number such that:
#
# Initially, if any number has less than four digits, it is padded with leading zeros.
# The ith digit (1 <= i <= 4) of the key is generated by taking the smallest digit among the ith digits of num1, num2,
# and num3.
# Return the key of the three numbers without leading zeros (if any).

class Solution:
    def generateKey(self, num1: int, num2: int, num3: int) -> int:
        nums = [
            str(num1).zfill(4),
            str(num2).zfill(4),
            str(num3).zfill(4)
        ]

        key = ""

        for i in range(4):
            key += min(nums[0][i], nums[1][i], nums[2][i])

        return int(key)
